[alembic]
# Göç dosyalarının saklanacağı klasör
script_location = migrations

# Canlı PostgreSQL veritabanı bağlantı adresimiz (Senkron Motor)
sqlalchemy.url = postgresql://fintrack_user:fintrack_password_123@db:5432/fintrack_db

# Günlükleme ve çıktı format ayarları
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S